#!/usr/bin/perl
use vars qw($APP $VERSION);
$APP     = 'c256';
$VERSION = 0.123;

use strict;
use Getopt::Long;
use Data::Dumper;
use Pod::Usage;

my $unicode = "░▒▓██▓▒░";
my @colors = map { sprintf("%3d", $_) } (0 .. 255);

our($opt_sqsize) = (16);

@ARGV or square($opt_sqsize);

GetOptions(
  'col:i'   => \$opt_sqsize,
  'list'    => \&list,
  'square'  => \&square,

  'help'      => sub { print "$APP v$VERSION\n\n"; pod2usage(verbose => 1)},
  'man'       => sub { pod2usage(verbose => 3)},
);

square($opt_sqsize);

sub square {
  my $col = shift // 16;
  my $end = int( 256/$col );
  my @colors = map { sprintf("%3d", $_) } (0 .. 255);

  for my $e(0 .. $end) {
    my @o;
    for( my $c = $e; $c < $colors[-1]; $c += $end + 1) {
      my $esc = "\e[48;5;$colors[$c]m$colors[$c]\e[0m";
      push(@o, $esc);
    }
    print "@o\n";
  }

  print "\n";
  exit 0;
}


sub list {
  for my $i(@colors) {
    printf("\e[38;5;%d%s %3d \e[48;5;$i%s %s %s %s \e[0m\n",
      $i, 'm', $i,  $unicode, $i);
  }
  exit 0;
}

=pod

=head1 NAME

colortest-256-ng - print various tables in 256 colors

=head1 USAGE

  c256 [-c columns] [OPTIONS]

=head1 DESCRIPTION

c256 will tell you if your terminal supports 256 colors.
It can also be used to see what color responds to what integer (0..255)

=head1 OPTIONS

  -s,   --square  square format (default)
  -l,   --list    list format
  -c,   --col     n columns

  -h    --help    help message
  -m    --man     view manpage

=head1 TRIVIA

The background notation to use is <ESC>38;5 - \033[38;5;100m

The foreground notation to use is <ESC>48;5 - \033[48;5;197m

=head1 AUTHOR

Written by Magnus Woldrich

=head1 COPYRIGHT

(C) Copyright 2010 Magnus Woldrich.

License GPLv2.

=cut
